language: node_js  #设置语言

node_js: stable  #设置相应的版本

cache:
    apt: true
    directories:
        - node_modules # 缓存不经常更改的内容

before_install:
    - export TZ='Asia/Shanghai' # 更改时区

install:
  - npm install  #安装hexo及插件

script:
  - hexo clean  #清除
  - hexo g && gulp  #生成

after_script:
  - git clone https://${GH_REF} .deploy_git  # GH_REF是最下面配置的仓库地址
  - cd .deploy_git
  - git checkout master
  - cd ../
  - mv .deploy_git/.git/ ./public/   # 这一步之前的操作是为了保留master分支的提交记录，不然每次git init的话只有1条commit
  - cd ./public
  - git config user.name "EXECUTER"  #修改name
  - git config user.email "chaosrinkhan@gmail.com"  #修改email
  - git add .
  - git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"  # 提交记录包含时间 跟上面更改时区配合
  - git push --force --quiet "https://${Travis_Token}@${GH_REF}" master:master  #Travis_Token是在Travis中配置环境变量的名称

branches:
  only:
    - master  #只监测master分支，master是我的分支的名称，可根据自己情况设置
env:
 global:
   - GH_REF: github.com/ChaosRinkHan/blog-source.git  #设置GH_REF，注意更改yourname
   - secure: "gWpKK9X+fjKTzBelZgbmk26v+VyshUZK+LlWzs2nxbb6UoWJcHz8/vN2UZ6auujGbViI4UsU2eHtXMLu39y00JPfigjNbKnlVd/oJjDHJCdozTxtOC5ZF5M4YAbM+XCw8Gggb6VHZQ1ybkOijdohubwu2QYmF3VxgMZM3YDLaMAHqWcsoCv9twjm+48YogP/u8hiMZp5LW0SHaDkTk4RNUtKnRYb5L8345p46Ot53iia1bc4sdskDMuq6CRmc9GiOZgOyzREYW5pU0iPhw+mUdCrTf6Xl8B1yU54OuQLVDwpseekmu2jcciBB1IDfF84IEUvNzgPxsCJgIBKVh19ZdQ24D4/juW65pOrVpeFAtsN9p7MNdgL/L3myeYr0tqVq+wp2SDJqgBX+rWEVoFxHNuOtEmtnfUTDRr7gLo7jPxoHGcvN7JpzxpzTcwIBNMPdCwx4DIhqHPRevEV8/oabc+EHQjzbJyx7uuJDT7a13xtGvGrWzdypuv7up7RchWff5E6Lokt2osTqN4vYTeBpam0Sc3muiM+aDi4ZYZPApgTc0lTyEff5D31Rm/KqUy2N4uNjMal10+pB8i5o/Y1O1A15QEl93UzrqVfwK+JHfEfXiQJwp9WaOeAuOEaQ1MbjgybOIF/A252FU5R1U2cX9fkNu0VPWdMfL+JcGHWALw="

# configure notifications (email, IRC, campfire etc)
# please update this section to your needs!
# https://docs.travis-ci.com/user/notifications/
notifications:
  email:
    - chaosrinkhan@gmail.com
  on_success: change
  on_failure: always
