language: node_js  #设置语言

node_js: stable  #设置相应的版本

cache:
    apt: true
    directories:
        - node_modules # 缓存不经常更改的内容

install:
  - npm install  #安装hexo及插件

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "exe"  #修改name
  - git config user.email "chaosrinkhan@gmail.com"  #修改email
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master  #Travis_Token是在Travis中配置环境变量的名称
branches:
  only:
    - master  #只监测master分支，master是我的分支的名称，可根据自己情况设置
env:
 global:
   - GH_REF: github.com/ChaosRinkHan/blog-source.git  #设置GH_REF，注意更改yourname
# configure notifications (email, IRC, campfire etc)
# please update this section to your needs!
# https://docs.travis-ci.com/user/notifications/
notifications:
  email:
    - chaosrinkhan@gmail.com
  on_success: change
  on_failure: always
